apiVersion: v1
kind: Service
metadata:
  name: nevin
  namespace: namespace-workflow-1710439780556
spec:
  type: LoadBalancer
  selector:
    app: nevin
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080